spring:
  datasource:
    url: jdbc:mysql://123.57.217.171:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
    hikari:
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
